#!/bin/sh
set -e

if [ "$1" = "remove" -o "$1" = "upgrade" ] ; then
	if PID=`pidof lscribed` ; then
		kill $PID
	fi
fi

if [ "$1" = "remove" ] ; then
	invoke-rc.d dbus reload
fi

#DEBHELPER#

exit 0


